version: '2'

services:
    postgres:
        container_name: cifra-postgres
        image: 'postgres:alpine'
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - /data/postgres/:/var/lib/postgresql/data
        # ports:
        #     - ${POSTGRES_PORT}:${POSTGRES_PORT}

    redis:
        container_name: cifra-redis
        image: "redis:alpine"
        restart: always
        volumes:
            - /data/redis/:/data
        # ports:
        #     - "${REDIS_PORT}:${REDIS_PORT}"
