version: '2'

services:
    postgres:
        container_name: cifra-postgres
        image: 'postgres:alpine'
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - /var/lib/postgresql/data:/data/postgres/
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        networks:
            - database

    pgAdmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "4400:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
        networks:
            - database

networks:
    database:
