version: '2'

services:
    postgres:
        container_name: cifra-postgres
        image: 'postgres:alpine'
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - /data/postgres/:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    pgAdmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "4400:4400"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

networks:
    backend:
