services:
    backend:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: integration-backend
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        volumes:
            - ../../static:/user/src/integration/backend/static
